### ISSUE TITLE
Suggestion to be added: explain how we farm - proof-of-blockstake #1

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/info_tftech_archived#15]
Original issue by @stelita.

On the .io website I would like to see explained how the TFTs are farmed and what's the technology making TFT mining green: talk about proof-of-blockstake.

As explained on the whitepaper: "The TF Chain has been built using our Rivine.io blockchain stack. It is a distributed, “proof-of-blockstake” blockchain. (...) ThreeFold farming is energy efficient due to its thin operating system and the proof-of-stake blockchain, both of which require little energy to operate. " I would also add Rob's comments "The proof of Blockstake is actually a proof of stake amongst proven validators, As such, it is a permissioned blockchain. The blockstake is the proof of being a validator. In this respect, it's actually a hybrid between Proof of stake and "proof of authority" , a terminology that did not exist when we created the proof of blockstake but that is gaining popularity for permissioned blockchains.
There is the Rivine whitepaper: https://github.com/rivine/rivine/blob/master/doc/whitepaper.md although it could use some updates to reflect the added features."

**Comment by VonSub** [comment]
@despiegk asked to put it up on the tech wiki in original issue found here:

https://github.com/threefoldfoundation/www_threefold.io/issues/1

**Comment by despiegk** [comment]
lets make sure we make it HUMAN friendly
